### ISSUE TITLE
Upgrade to 10.16 with new angular version

### ISSUE THREAD

**Issue by mbay-ODW** [SoftwareAG/cumulocity-analytics-management#2]
Currently the plugin works for version up to 10.15.
Since 10.16 has new angular version, plugin needs to be upgraded.

**Comment by sagIoTPower** [comment]
@mbay-ODW: Thank you very raising this issue. The [latest version](https://github.com/SoftwareAG/cumulocity-analytics-management/releases/tag/v2.1.6) is upgraded to 10.18.
